# .github/workflows/deploy.yml
name: Deploy to Lovable AI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run deployment script
        run: node lovable-deploy.js
        env:
          LOVABLE_EMAIL: ${{ secrets.LOVABLE_EMAIL }}
          LOVABLE_PASSWORD: ${{ secrets.LOVABLE_PASSWORD }}